### ISSUE TITLE
backend bug 

### ISSUE THREAD

**Issue by Asem-Assi** [IsAmitprajapati/Full-Stack-E-Commerce-MERN-APP#1]
thanks man, i think there is a bug in addToCart controller in the check the availability of product
it must be like this:        const isProductAvailable =  await addToCartModel.findOne({ productId, userId: currentUser });
 

insted of:        const isProductAvailable =  await addToCartModel.findOne({ productId});

**Comment by IsAmitprajapati** [comment]
yes bro, In next video i will solve this

**Comment by JatinAhirwar** [comment]
Thank u brother for figure it out 
I will also take a look at this
