### ISSUE TITLE
Sign up 

### ISSUE THREAD

**Issue by akg568794** [IsAmitprajapati/Full-Stack-E-Commerce-MERN-APP#5]
There is a bug that occurs when the profile image is uploaded for the signup.

SignUp.js:53 
        
POST https://payment-order-full-stack-ecommerce.vercel.app/api/signup 413 (Payload Too Large)
onSubmit @ SignUp.js:53

VM116:1 Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

**Comment by IsAmitprajapati** [comment]
in the index.js file you want to increase the payload limit app.use(express.json({limit : '50mb'))
