### ISSUE TITLE
Loading and failed to fetch

### ISSUE THREAD

**Issue by ROHIT-code-6363** [IsAmitprajapati/Full-Stack-E-Commerce-MERN-APP#8]
![IMG_20241019_111644.jpg](https://github.com/user-attachments/assets/6c5ce097-c26a-4186-87be-64393606ab33)

![IMG_20241019_111403.jpg](https://github.com/user-attachments/assets/8bd47bc7-6833-4c16-9f88-64ef8cf852c2)

I already installed cors
And in backend rapidApi is working
Url also same backend and frontend

**Comment by SalimOsome** [comment]
having the same problem ,have you silve it
